"""what the crawl knew about a show

Revision ID: 0cecc18e241a
Revises: 83ba5beb7e0f
Create Date: 2026-08-17 22:49:39.258572
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0cecc18e241a'
down_revision: str | None = '83ba5beb7e0f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('original_title', sa.String(length=300), nullable=True))
    op.add_column('shows', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('shows', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('shows', sa.Column('duration', sa.String(length=60), nullable=True))
    op.add_column('shows', sa.Column('age_rating', sa.String(length=20), nullable=True))
    op.add_column('shows', sa.Column('genres', sa.JSON(), nullable=True))
    op.add_column('shows', sa.Column('countries', sa.JSON(), nullable=True))
    op.add_column('shows', sa.Column('directors', sa.JSON(), nullable=True))
    op.add_column('shows', sa.Column('starring', sa.JSON(), nullable=True))
    op.add_column('shows', sa.Column('imdb_id', sa.String(length=12), nullable=True))
    op.add_column('shows', sa.Column('imdb_rating', sa.Float(), nullable=True))
    op.add_column('shows', sa.Column('imdb_votes', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_shows_imdb_id'), 'shows', ['imdb_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shows_imdb_id'), table_name='shows')
    op.drop_column('shows', 'imdb_votes')
    op.drop_column('shows', 'imdb_rating')
    op.drop_column('shows', 'imdb_id')
    op.drop_column('shows', 'starring')
    op.drop_column('shows', 'directors')
    op.drop_column('shows', 'countries')
    op.drop_column('shows', 'genres')
    op.drop_column('shows', 'age_rating')
    op.drop_column('shows', 'duration')
    op.drop_column('shows', 'description')
    op.drop_column('shows', 'year')
    op.drop_column('shows', 'original_title')
    # ### end Alembic commands ###
