"""drop stored vod_url

Revision ID: 3851c7cb6cb3
Revises: b2e95cf16692
Create Date: 2026-08-17 14:19:41.515230
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3851c7cb6cb3'
down_revision: str | None = 'b2e95cf16692'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episodes', 'vod_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('vod_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
