"""browse by year

Revision ID: 703a6a2b7481
Revises: d25843680d5d
Create Date: 2026-08-18 00:39:53.043231
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '703a6a2b7481'
down_revision: str | None = 'd25843680d5d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_shows_year'), 'shows', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shows_year'), table_name='shows')
    # ### end Alembic commands ###
