"""an episode can be dubbed twice

Revision ID: 8126285b067a
Revises: 703a6a2b7481
Create Date: 2026-08-18 00:53:17.679320
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8126285b067a'
down_revision: str | None = '703a6a2b7481'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episode_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('vod_id', sa.Integer(), nullable=False),
    sa.Column('audio', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episode_tracks_episode_id'), 'episode_tracks', ['episode_id'], unique=False)
    op.create_index(op.f('ix_episode_tracks_vod_id'), 'episode_tracks', ['vod_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episode_tracks_vod_id'), table_name='episode_tracks')
    op.drop_index(op.f('ix_episode_tracks_episode_id'), table_name='episode_tracks')
    op.drop_table('episode_tracks')
    # ### end Alembic commands ###
