"""the whole schema

Everything in one revision: shows and episodes, playlists, users and their
sessions, watch progress and activity, uploaded media, home sections and their
artwork. The five revisions that built it up one feature at a time were
collapsed into this one before anything ran outside a laptop — their history was
a record of how the schema was written, not of how any database got here.

That makes this a hard cut. A database still stamped with one of the old
revisions cannot be upgraded across the gap: its schema is already this one, so
`alembic stamp 83ba5beb7e0f` is the move, and `alembic upgrade head` on an empty
database is the other. There is nothing in between to migrate.

Revision ID: 83ba5beb7e0f
Revises:
Create Date: 2026-08-17 21:34:48.651811
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '83ba5beb7e0f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('poster', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shows_key'), 'shows', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role', native_enum=False, length=20), server_default='user', nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_table('activity_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('subject_type', sa.String(length=30), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_events_type'), 'activity_events', ['type'], unique=False)
    op.create_index(op.f('ix_activity_events_user_id'), 'activity_events', ['user_id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_token_hash'), 'auth_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('episode_end', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('poster', sa.String(length=1000), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('vod_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('show_id', 'season', 'episode', name='uq_episode_number')
    )
    op.create_index(op.f('ix_episodes_show_id'), 'episodes', ['show_id'], unique=False)
    op.create_index(op.f('ix_episodes_source_url'), 'episodes', ['source_url'], unique=True)
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('extension', sa.String(length=8), nullable=False),
    sa.Column('content_type', sa.String(length=60), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('original_name', sa.String(length=300), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_files_digest'), 'media_files', ['digest'], unique=True)
    op.create_index(op.f('ix_media_files_uploaded_by_id'), 'media_files', ['uploaded_by_id'], unique=False)
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'public', name='playlist_visibility', native_enum=False, length=20), server_default='private', nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlists_owner_id'), 'playlists', ['owner_id'], unique=False)
    op.create_index(op.f('ix_playlists_visibility'), 'playlists', ['visibility'], unique=False)
    op.create_table('playlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playlist_id', 'episode_id', name='uq_playlist_episode')
    )
    op.create_index(op.f('ix_playlist_items_playlist_id'), 'playlist_items', ['playlist_id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('hero', 'rail', 'grid', 'banner', name='section_kind', native_enum=False, length=20), server_default='rail', nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('kicker', sa.String(length=200), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('item_limit', sa.Integer(), server_default='14', nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT (show_id IS NOT NULL AND playlist_id IS NOT NULL)', name='ck_section_one_source'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_playlist_id'), 'sections', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_sections_position'), 'sections', ['position'], unique=False)
    op.create_index(op.f('ix_sections_show_id'), 'sections', ['show_id'], unique=False)
    op.create_table('watch_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('position_seconds', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_watched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'episode_id', name='uq_progress_user_episode')
    )
    op.create_index(op.f('ix_watch_progress_episode_id'), 'watch_progress', ['episode_id'], unique=False)
    op.create_index(op.f('ix_watch_progress_last_watched_at'), 'watch_progress', ['last_watched_at'], unique=False)
    op.create_index(op.f('ix_watch_progress_user_id'), 'watch_progress', ['user_id'], unique=False)
    op.create_table('artwork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placement', sa.Enum('hero', 'tile', 'poster', 'square', 'logo', name='artwork_placement', native_enum=False, length=20), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(CASE WHEN show_id IS NULL THEN 0 ELSE 1 END) + (CASE WHEN playlist_id IS NULL THEN 0 ELSE 1 END) + (CASE WHEN section_id IS NULL THEN 0 ELSE 1 END) = 1', name='ck_artwork_one_subject'),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playlist_id', 'placement', name='uq_artwork_playlist_placement'),
    sa.UniqueConstraint('section_id', 'placement', name='uq_artwork_section_placement'),
    sa.UniqueConstraint('show_id', 'placement', name='uq_artwork_show_placement')
    )
    op.create_index(op.f('ix_artwork_media_id'), 'artwork', ['media_id'], unique=False)
    op.create_index(op.f('ix_artwork_placement'), 'artwork', ['placement'], unique=False)
    op.create_index(op.f('ix_artwork_playlist_id'), 'artwork', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_artwork_section_id'), 'artwork', ['section_id'], unique=False)
    op.create_index(op.f('ix_artwork_show_id'), 'artwork', ['show_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artwork_show_id'), table_name='artwork')
    op.drop_index(op.f('ix_artwork_section_id'), table_name='artwork')
    op.drop_index(op.f('ix_artwork_playlist_id'), table_name='artwork')
    op.drop_index(op.f('ix_artwork_placement'), table_name='artwork')
    op.drop_index(op.f('ix_artwork_media_id'), table_name='artwork')
    op.drop_table('artwork')
    op.drop_index(op.f('ix_watch_progress_user_id'), table_name='watch_progress')
    op.drop_index(op.f('ix_watch_progress_last_watched_at'), table_name='watch_progress')
    op.drop_index(op.f('ix_watch_progress_episode_id'), table_name='watch_progress')
    op.drop_table('watch_progress')
    op.drop_index(op.f('ix_sections_show_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_position'), table_name='sections')
    op.drop_index(op.f('ix_sections_playlist_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_playlist_items_playlist_id'), table_name='playlist_items')
    op.drop_table('playlist_items')
    op.drop_index(op.f('ix_playlists_visibility'), table_name='playlists')
    op.drop_index(op.f('ix_playlists_owner_id'), table_name='playlists')
    op.drop_table('playlists')
    op.drop_index(op.f('ix_media_files_uploaded_by_id'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_digest'), table_name='media_files')
    op.drop_table('media_files')
    op.drop_index(op.f('ix_episodes_source_url'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_show_id'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_token_hash'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_activity_events_user_id'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_type'), table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shows_key'), table_name='shows')
    op.drop_table('shows')
    # ### end Alembic commands ###
