"""language on a track

What language a stream is *in*, which the dub's name never says: a studio is not
a language, and HLS carries no tag for one. It comes from the crawler — a site
publishes in one language — so it arrives with the VOD envelope and lands here.

Nullable because it genuinely can be unknown: an original soundtrack, in a
language the crawl never learned.

Revision ID: 8ec0ee44e53d
Revises: 8126285b067a
Create Date: 2026-08-19 12:47:31.690071
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8ec0ee44e53d'
down_revision: str | None = '8126285b067a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode_tracks', sa.Column('language', sa.String(length=8), nullable=True))
    op.create_index(op.f('ix_episode_tracks_language'), 'episode_tracks', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episode_tracks_language'), table_name='episode_tracks')
    op.drop_column('episode_tracks', 'language')
    # ### end Alembic commands ###
