"""a television asks a phone to sign it in

Revision ID: 92f46009f9cd
Revises: fbe55e8e976c
Create Date: 2026-08-19 14:51:25.332150
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '92f46009f9cd'
down_revision: str | None = 'fbe55e8e976c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('secret_digest', sa.String(length=64), nullable=False),
    sa.Column('device_name', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_links_code'), 'device_links', ['code'], unique=True)
    op.create_index(op.f('ix_device_links_secret_digest'), 'device_links', ['secret_digest'], unique=True)
    op.create_index(op.f('ix_device_links_user_id'), 'device_links', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_links_user_id'), table_name='device_links')
    op.drop_index(op.f('ix_device_links_secret_digest'), table_name='device_links')
    op.drop_index(op.f('ix_device_links_code'), table_name='device_links')
    op.drop_table('device_links')
    # ### end Alembic commands ###
