"""shows and episodes

Revision ID: 9ffb4d18f40a
Revises: 
Create Date: 2026-08-16 21:16:45.685409
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9ffb4d18f40a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('poster', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shows_key'), 'shows', ['key'], unique=True)
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('episode_end', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('poster', sa.String(length=1000), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('vod_id', sa.Integer(), nullable=True),
    sa.Column('vod_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('show_id', 'season', 'episode', name='uq_episode_number')
    )
    op.create_index(op.f('ix_episodes_show_id'), 'episodes', ['show_id'], unique=False)
    op.create_index(op.f('ix_episodes_source_url'), 'episodes', ['source_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episodes_source_url'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_show_id'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_shows_key'), table_name='shows')
    op.drop_table('shows')
    # ### end Alembic commands ###
