"""a film can carry every dub it ever got

Revision ID: d25843680d5d
Revises: d9a283903420
Create Date: 2026-08-18 00:31:53.940947
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd25843680d5d'
down_revision: str | None = 'd9a283903420'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'audio',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'audio',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###
