"""kind, audio and quality on a show

Revision ID: d9a283903420
Revises: e1daa41646a7
Create Date: 2026-08-18 00:29:23.170568
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd9a283903420'
down_revision: str | None = 'e1daa41646a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('kind', sa.String(length=20), nullable=True))
    op.add_column('shows', sa.Column('year_end', sa.Integer(), nullable=True))
    op.add_column('shows', sa.Column('audio', sa.String(length=200), nullable=True))
    op.add_column('shows', sa.Column('quality', sa.String(length=40), nullable=True))
    op.create_index(op.f('ix_shows_kind'), 'shows', ['kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shows_kind'), table_name='shows')
    op.drop_column('shows', 'quality')
    op.drop_column('shows', 'audio')
    op.drop_column('shows', 'year_end')
    op.drop_column('shows', 'kind')
    # ### end Alembic commands ###
