"""where the catalogue got to in the vod list

Revision ID: e1daa41646a7
Revises: 0cecc18e241a
Create Date: 2026-08-18 00:13:31.459044
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e1daa41646a7'
down_revision: str | None = '0cecc18e241a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_cursors',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_cursors')
    # ### end Alembic commands ###
