"""a dub line is as long as the source made it

Revision ID: fbe55e8e976c
Revises: 8ec0ee44e53d
Create Date: 2026-08-19 12:58:41.373055
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'fbe55e8e976c'
down_revision: str | None = '8ec0ee44e53d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('episode_tracks', 'audio',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('episode_tracks', 'audio',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###
