# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts import catalogue_pb2 as contracts_dot_catalogue__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in contracts/catalogue_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AccountsStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WhoAmI = channel.unary_unary(
                '/catalogue.v1.Accounts/WhoAmI',
                request_serializer=contracts_dot_catalogue__pb2.WhoAmIRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.Identity.FromString,
                _registered_method=True)
        self.StartGuest = channel.unary_unary(
                '/catalogue.v1.Accounts/StartGuest',
                request_serializer=contracts_dot_catalogue__pb2.StartGuestRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.Identity.FromString,
                _registered_method=True)
        self.Claim = channel.unary_unary(
                '/catalogue.v1.Accounts/Claim',
                request_serializer=contracts_dot_catalogue__pb2.ClaimRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.Identity.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/catalogue.v1.Accounts/Login',
                request_serializer=contracts_dot_catalogue__pb2.LoginRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.Identity.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/catalogue.v1.Accounts/Logout',
                request_serializer=contracts_dot_catalogue__pb2.LogoutRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.Rename = channel.unary_unary(
                '/catalogue.v1.Accounts/Rename',
                request_serializer=contracts_dot_catalogue__pb2.RenameRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.User.FromString,
                _registered_method=True)
        self.StartDeviceLink = channel.unary_unary(
                '/catalogue.v1.Accounts/StartDeviceLink',
                request_serializer=contracts_dot_catalogue__pb2.StartDeviceLinkRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.DeviceLink.FromString,
                _registered_method=True)
        self.CollectDeviceLink = channel.unary_unary(
                '/catalogue.v1.Accounts/CollectDeviceLink',
                request_serializer=contracts_dot_catalogue__pb2.CollectDeviceLinkRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.DeviceSession.FromString,
                _registered_method=True)


class AccountsServicer:
    """Missing associated documentation comment in .proto file."""

    def WhoAmI(self, request, context):
        """Who am I — minting a guest if the answer would have been nobody.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartGuest(self, request, context):
        """A *new* guest, even if the caller already had one. That's what makes it
        usable as "watch as someone else on the shared TV".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Claim(self, request, context):
        """Keep the account, add the login: the guest row gains an email and a
        password, so nothing watched so far is lost.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rename(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartDeviceLink(self, request, context):
        """Signing in a device that has no keyboard.

        A television asks for a code, shows it (as a QR, usually), and waits. A
        phone opens that code in a browser and approves it as whoever is signed in
        there. Then the television collects a session of its own.

        Approval is deliberately not here: it happens in a browser, where somebody
        is already signed in and can see what they are agreeing to.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectDeviceLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WhoAmI': grpc.unary_unary_rpc_method_handler(
                    servicer.WhoAmI,
                    request_deserializer=contracts_dot_catalogue__pb2.WhoAmIRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.Identity.SerializeToString,
            ),
            'StartGuest': grpc.unary_unary_rpc_method_handler(
                    servicer.StartGuest,
                    request_deserializer=contracts_dot_catalogue__pb2.StartGuestRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.Identity.SerializeToString,
            ),
            'Claim': grpc.unary_unary_rpc_method_handler(
                    servicer.Claim,
                    request_deserializer=contracts_dot_catalogue__pb2.ClaimRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.Identity.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=contracts_dot_catalogue__pb2.LoginRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.Identity.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=contracts_dot_catalogue__pb2.LogoutRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.LogoutResponse.SerializeToString,
            ),
            'Rename': grpc.unary_unary_rpc_method_handler(
                    servicer.Rename,
                    request_deserializer=contracts_dot_catalogue__pb2.RenameRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.User.SerializeToString,
            ),
            'StartDeviceLink': grpc.unary_unary_rpc_method_handler(
                    servicer.StartDeviceLink,
                    request_deserializer=contracts_dot_catalogue__pb2.StartDeviceLinkRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.DeviceLink.SerializeToString,
            ),
            'CollectDeviceLink': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectDeviceLink,
                    request_deserializer=contracts_dot_catalogue__pb2.CollectDeviceLinkRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.DeviceSession.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'catalogue.v1.Accounts', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('catalogue.v1.Accounts', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Accounts:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WhoAmI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Accounts/WhoAmI',
            contracts_dot_catalogue__pb2.WhoAmIRequest.SerializeToString,
            contracts_dot_catalogue__pb2.Identity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartGuest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Accounts/StartGuest',
            contracts_dot_catalogue__pb2.StartGuestRequest.SerializeToString,
            contracts_dot_catalogue__pb2.Identity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Claim(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Accounts/Claim',
            contracts_dot_catalogue__pb2.ClaimRequest.SerializeToString,
            contracts_dot_catalogue__pb2.Identity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Accounts/Login',
            contracts_dot_catalogue__pb2.LoginRequest.SerializeToString,
            contracts_dot_catalogue__pb2.Identity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Accounts/Logout',
            contracts_dot_catalogue__pb2.LogoutRequest.SerializeToString,
            contracts_dot_catalogue__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rename(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Accounts/Rename',
            contracts_dot_catalogue__pb2.RenameRequest.SerializeToString,
            contracts_dot_catalogue__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartDeviceLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Accounts/StartDeviceLink',
            contracts_dot_catalogue__pb2.StartDeviceLinkRequest.SerializeToString,
            contracts_dot_catalogue__pb2.DeviceLink.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectDeviceLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Accounts/CollectDeviceLink',
            contracts_dot_catalogue__pb2.CollectDeviceLinkRequest.SerializeToString,
            contracts_dot_catalogue__pb2.DeviceSession.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CatalogueStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/catalogue.v1.Catalogue/Health',
                request_serializer=contracts_dot_catalogue__pb2.HealthRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ListShows = channel.unary_unary(
                '/catalogue.v1.Catalogue/ListShows',
                request_serializer=contracts_dot_catalogue__pb2.ListShowsRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.ListShowsResponse.FromString,
                _registered_method=True)
        self.GetShow = channel.unary_unary(
                '/catalogue.v1.Catalogue/GetShow',
                request_serializer=contracts_dot_catalogue__pb2.GetShowRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.ShowWithEpisodes.FromString,
                _registered_method=True)
        self.StreamShows = channel.unary_stream(
                '/catalogue.v1.Catalogue/StreamShows',
                request_serializer=contracts_dot_catalogue__pb2.StreamShowsRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.ShowSummary.FromString,
                _registered_method=True)
        self.ListEpisodes = channel.unary_unary(
                '/catalogue.v1.Catalogue/ListEpisodes',
                request_serializer=contracts_dot_catalogue__pb2.ListEpisodesRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.ListEpisodesResponse.FromString,
                _registered_method=True)
        self.GetEpisode = channel.unary_unary(
                '/catalogue.v1.Catalogue/GetEpisode',
                request_serializer=contracts_dot_catalogue__pb2.GetEpisodeRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.EpisodeWithShow.FromString,
                _registered_method=True)
        self.GetHome = channel.unary_unary(
                '/catalogue.v1.Catalogue/GetHome',
                request_serializer=contracts_dot_catalogue__pb2.GetHomeRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.Home.FromString,
                _registered_method=True)


class CatalogueServicer:
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListShows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShow(self, request, context):
        """Everything on one show's page: what the crawl knew, plus its episodes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamShows(self, request, context):
        """The whole catalogue, a show at a time.

        Paging exists because a browse screen wants a screenful; this exists
        because a phone that wants to search offline wants all eight thousand, and
        asking for them 50 at a time is 160 round trips. One call, one stream, and
        the client can draw the first rows before the last ones are read.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEpisodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEpisode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHome(self, request, context):
        """The front page, as a person arranged it. One call for the whole screen.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogueServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=contracts_dot_catalogue__pb2.HealthRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.HealthResponse.SerializeToString,
            ),
            'ListShows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListShows,
                    request_deserializer=contracts_dot_catalogue__pb2.ListShowsRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.ListShowsResponse.SerializeToString,
            ),
            'GetShow': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShow,
                    request_deserializer=contracts_dot_catalogue__pb2.GetShowRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.ShowWithEpisodes.SerializeToString,
            ),
            'StreamShows': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamShows,
                    request_deserializer=contracts_dot_catalogue__pb2.StreamShowsRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.ShowSummary.SerializeToString,
            ),
            'ListEpisodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEpisodes,
                    request_deserializer=contracts_dot_catalogue__pb2.ListEpisodesRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.ListEpisodesResponse.SerializeToString,
            ),
            'GetEpisode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEpisode,
                    request_deserializer=contracts_dot_catalogue__pb2.GetEpisodeRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.EpisodeWithShow.SerializeToString,
            ),
            'GetHome': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHome,
                    request_deserializer=contracts_dot_catalogue__pb2.GetHomeRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.Home.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'catalogue.v1.Catalogue', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('catalogue.v1.Catalogue', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Catalogue:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Catalogue/Health',
            contracts_dot_catalogue__pb2.HealthRequest.SerializeToString,
            contracts_dot_catalogue__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListShows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Catalogue/ListShows',
            contracts_dot_catalogue__pb2.ListShowsRequest.SerializeToString,
            contracts_dot_catalogue__pb2.ListShowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Catalogue/GetShow',
            contracts_dot_catalogue__pb2.GetShowRequest.SerializeToString,
            contracts_dot_catalogue__pb2.ShowWithEpisodes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamShows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/catalogue.v1.Catalogue/StreamShows',
            contracts_dot_catalogue__pb2.StreamShowsRequest.SerializeToString,
            contracts_dot_catalogue__pb2.ShowSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEpisodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Catalogue/ListEpisodes',
            contracts_dot_catalogue__pb2.ListEpisodesRequest.SerializeToString,
            contracts_dot_catalogue__pb2.ListEpisodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEpisode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Catalogue/GetEpisode',
            contracts_dot_catalogue__pb2.GetEpisodeRequest.SerializeToString,
            contracts_dot_catalogue__pb2.EpisodeWithShow.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Catalogue/GetHome',
            contracts_dot_catalogue__pb2.GetHomeRequest.SerializeToString,
            contracts_dot_catalogue__pb2.Home.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WatchingStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportProgress = channel.unary_unary(
                '/catalogue.v1.Watching/ReportProgress',
                request_serializer=contracts_dot_catalogue__pb2.ReportProgressRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.Progress.FromString,
                _registered_method=True)
        self.GetProgress = channel.unary_unary(
                '/catalogue.v1.Watching/GetProgress',
                request_serializer=contracts_dot_catalogue__pb2.GetProgressRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.Progress.FromString,
                _registered_method=True)
        self.ForgetProgress = channel.unary_unary(
                '/catalogue.v1.Watching/ForgetProgress',
                request_serializer=contracts_dot_catalogue__pb2.ForgetProgressRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.ForgetProgressResponse.FromString,
                _registered_method=True)
        self.ListHistory = channel.unary_unary(
                '/catalogue.v1.Watching/ListHistory',
                request_serializer=contracts_dot_catalogue__pb2.ListHistoryRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.ListHistoryResponse.FromString,
                _registered_method=True)
        self.ContinueWatching = channel.unary_unary(
                '/catalogue.v1.Watching/ContinueWatching',
                request_serializer=contracts_dot_catalogue__pb2.ContinueWatchingRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.ContinueWatchingResponse.FromString,
                _registered_method=True)


class WatchingServicer:
    """Missing associated documentation comment in .proto file."""

    def ReportProgress(self, request, context):
        """The player checking in. Sent often — keep it small.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProgress(self, request, context):
        """Where to seek to when the player opens. NOT_FOUND means "start at zero".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForgetProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ContinueWatching(self, request, context):
        """Started, not finished, newest first — the rail on the home screen.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WatchingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportProgress,
                    request_deserializer=contracts_dot_catalogue__pb2.ReportProgressRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.Progress.SerializeToString,
            ),
            'GetProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProgress,
                    request_deserializer=contracts_dot_catalogue__pb2.GetProgressRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.Progress.SerializeToString,
            ),
            'ForgetProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.ForgetProgress,
                    request_deserializer=contracts_dot_catalogue__pb2.ForgetProgressRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.ForgetProgressResponse.SerializeToString,
            ),
            'ListHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.ListHistory,
                    request_deserializer=contracts_dot_catalogue__pb2.ListHistoryRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.ListHistoryResponse.SerializeToString,
            ),
            'ContinueWatching': grpc.unary_unary_rpc_method_handler(
                    servicer.ContinueWatching,
                    request_deserializer=contracts_dot_catalogue__pb2.ContinueWatchingRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.ContinueWatchingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'catalogue.v1.Watching', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('catalogue.v1.Watching', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Watching:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReportProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Watching/ReportProgress',
            contracts_dot_catalogue__pb2.ReportProgressRequest.SerializeToString,
            contracts_dot_catalogue__pb2.Progress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Watching/GetProgress',
            contracts_dot_catalogue__pb2.GetProgressRequest.SerializeToString,
            contracts_dot_catalogue__pb2.Progress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForgetProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Watching/ForgetProgress',
            contracts_dot_catalogue__pb2.ForgetProgressRequest.SerializeToString,
            contracts_dot_catalogue__pb2.ForgetProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Watching/ListHistory',
            contracts_dot_catalogue__pb2.ListHistoryRequest.SerializeToString,
            contracts_dot_catalogue__pb2.ListHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ContinueWatching(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Watching/ContinueWatching',
            contracts_dot_catalogue__pb2.ContinueWatchingRequest.SerializeToString,
            contracts_dot_catalogue__pb2.ContinueWatchingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PlaylistsStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListPlaylists = channel.unary_unary(
                '/catalogue.v1.Playlists/ListPlaylists',
                request_serializer=contracts_dot_catalogue__pb2.ListPlaylistsRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.ListPlaylistsResponse.FromString,
                _registered_method=True)
        self.GetPlaylist = channel.unary_unary(
                '/catalogue.v1.Playlists/GetPlaylist',
                request_serializer=contracts_dot_catalogue__pb2.GetPlaylistRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.PlaylistDetail.FromString,
                _registered_method=True)
        self.CreatePlaylist = channel.unary_unary(
                '/catalogue.v1.Playlists/CreatePlaylist',
                request_serializer=contracts_dot_catalogue__pb2.CreatePlaylistRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.PlaylistDetail.FromString,
                _registered_method=True)
        self.CreateFromShow = channel.unary_unary(
                '/catalogue.v1.Playlists/CreateFromShow',
                request_serializer=contracts_dot_catalogue__pb2.CreateFromShowRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.PlaylistDetail.FromString,
                _registered_method=True)
        self.UpdatePlaylist = channel.unary_unary(
                '/catalogue.v1.Playlists/UpdatePlaylist',
                request_serializer=contracts_dot_catalogue__pb2.UpdatePlaylistRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.PlaylistDetail.FromString,
                _registered_method=True)
        self.DeletePlaylist = channel.unary_unary(
                '/catalogue.v1.Playlists/DeletePlaylist',
                request_serializer=contracts_dot_catalogue__pb2.DeletePlaylistRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.DeletePlaylistResponse.FromString,
                _registered_method=True)
        self.AddItem = channel.unary_unary(
                '/catalogue.v1.Playlists/AddItem',
                request_serializer=contracts_dot_catalogue__pb2.AddItemRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.PlaylistDetail.FromString,
                _registered_method=True)
        self.RemoveItem = channel.unary_unary(
                '/catalogue.v1.Playlists/RemoveItem',
                request_serializer=contracts_dot_catalogue__pb2.RemoveItemRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.PlaylistDetail.FromString,
                _registered_method=True)
        self.Reorder = channel.unary_unary(
                '/catalogue.v1.Playlists/Reorder',
                request_serializer=contracts_dot_catalogue__pb2.ReorderRequest.SerializeToString,
                response_deserializer=contracts_dot_catalogue__pb2.PlaylistDetail.FromString,
                _registered_method=True)


class PlaylistsServicer:
    """Missing associated documentation comment in .proto file."""

    def ListPlaylists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFromShow(self, request, context):
        """A season, or a whole show, in one call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reorder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlaylistsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListPlaylists': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlaylists,
                    request_deserializer=contracts_dot_catalogue__pb2.ListPlaylistsRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.ListPlaylistsResponse.SerializeToString,
            ),
            'GetPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaylist,
                    request_deserializer=contracts_dot_catalogue__pb2.GetPlaylistRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.PlaylistDetail.SerializeToString,
            ),
            'CreatePlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePlaylist,
                    request_deserializer=contracts_dot_catalogue__pb2.CreatePlaylistRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.PlaylistDetail.SerializeToString,
            ),
            'CreateFromShow': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFromShow,
                    request_deserializer=contracts_dot_catalogue__pb2.CreateFromShowRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.PlaylistDetail.SerializeToString,
            ),
            'UpdatePlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePlaylist,
                    request_deserializer=contracts_dot_catalogue__pb2.UpdatePlaylistRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.PlaylistDetail.SerializeToString,
            ),
            'DeletePlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePlaylist,
                    request_deserializer=contracts_dot_catalogue__pb2.DeletePlaylistRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.DeletePlaylistResponse.SerializeToString,
            ),
            'AddItem': grpc.unary_unary_rpc_method_handler(
                    servicer.AddItem,
                    request_deserializer=contracts_dot_catalogue__pb2.AddItemRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.PlaylistDetail.SerializeToString,
            ),
            'RemoveItem': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveItem,
                    request_deserializer=contracts_dot_catalogue__pb2.RemoveItemRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.PlaylistDetail.SerializeToString,
            ),
            'Reorder': grpc.unary_unary_rpc_method_handler(
                    servicer.Reorder,
                    request_deserializer=contracts_dot_catalogue__pb2.ReorderRequest.FromString,
                    response_serializer=contracts_dot_catalogue__pb2.PlaylistDetail.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'catalogue.v1.Playlists', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('catalogue.v1.Playlists', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Playlists:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListPlaylists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Playlists/ListPlaylists',
            contracts_dot_catalogue__pb2.ListPlaylistsRequest.SerializeToString,
            contracts_dot_catalogue__pb2.ListPlaylistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Playlists/GetPlaylist',
            contracts_dot_catalogue__pb2.GetPlaylistRequest.SerializeToString,
            contracts_dot_catalogue__pb2.PlaylistDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Playlists/CreatePlaylist',
            contracts_dot_catalogue__pb2.CreatePlaylistRequest.SerializeToString,
            contracts_dot_catalogue__pb2.PlaylistDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFromShow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Playlists/CreateFromShow',
            contracts_dot_catalogue__pb2.CreateFromShowRequest.SerializeToString,
            contracts_dot_catalogue__pb2.PlaylistDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Playlists/UpdatePlaylist',
            contracts_dot_catalogue__pb2.UpdatePlaylistRequest.SerializeToString,
            contracts_dot_catalogue__pb2.PlaylistDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Playlists/DeletePlaylist',
            contracts_dot_catalogue__pb2.DeletePlaylistRequest.SerializeToString,
            contracts_dot_catalogue__pb2.DeletePlaylistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Playlists/AddItem',
            contracts_dot_catalogue__pb2.AddItemRequest.SerializeToString,
            contracts_dot_catalogue__pb2.PlaylistDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Playlists/RemoveItem',
            contracts_dot_catalogue__pb2.RemoveItemRequest.SerializeToString,
            contracts_dot_catalogue__pb2.PlaylistDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reorder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogue.v1.Playlists/Reorder',
            contracts_dot_catalogue__pb2.ReorderRequest.SerializeToString,
            contracts_dot_catalogue__pb2.PlaylistDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
