# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/vod.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'contracts/vod.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ontracts/vod.proto\x12\x06vod.v1\"V\n\x08Metadata\x12\x12\n\x05title\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06poster\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x0c\n\x04json\x18\x03 \x01(\tB\x08\n\x06_titleB\t\n\x07_poster\"l\n\x03Vod\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x14\n\x0cplaylist_url\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\"\n\x08metadata\x18\x04 \x01(\x0b\x32\x10.vod.v1.Metadata\x12\x12\n\ncreated_at\x18\x05 \x01(\t\"L\n\x10\x43reateVodRequest\x12\x14\n\x0cplaylist_url\x18\x01 \x01(\t\x12\"\n\x08metadata\x18\x02 \x01(\x0b\x32\x10.vod.v1.Metadata\">\n\x11\x43reateVodResponse\x12\x18\n\x03vod\x18\x01 \x01(\x0b\x32\x0b.vod.v1.Vod\x12\x0f\n\x07\x63reated\x18\x02 \x01(\x08\"\x1b\n\rGetVodRequest\x12\n\n\x02id\x18\x01 \x01(\x04\"2\n\x0fListVodsRequest\x12\r\n\x05limit\x18\x01 \x01(\r\x12\x10\n\x08\x61\x66ter_id\x18\x02 \x01(\x04\"-\n\x10ListVodsResponse\x12\x19\n\x04vods\x18\x01 \x03(\x0b\x32\x0b.vod.v1.Vod2\xbb\x01\n\nVodService\x12@\n\tCreateVod\x12\x18.vod.v1.CreateVodRequest\x1a\x19.vod.v1.CreateVodResponse\x12,\n\x06GetVod\x12\x15.vod.v1.GetVodRequest\x1a\x0b.vod.v1.Vod\x12=\n\x08ListVods\x12\x17.vod.v1.ListVodsRequest\x1a\x18.vod.v1.ListVodsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.vod_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METADATA']._serialized_start=31
  _globals['_METADATA']._serialized_end=117
  _globals['_VOD']._serialized_start=119
  _globals['_VOD']._serialized_end=227
  _globals['_CREATEVODREQUEST']._serialized_start=229
  _globals['_CREATEVODREQUEST']._serialized_end=305
  _globals['_CREATEVODRESPONSE']._serialized_start=307
  _globals['_CREATEVODRESPONSE']._serialized_end=369
  _globals['_GETVODREQUEST']._serialized_start=371
  _globals['_GETVODREQUEST']._serialized_end=398
  _globals['_LISTVODSREQUEST']._serialized_start=400
  _globals['_LISTVODSREQUEST']._serialized_end=450
  _globals['_LISTVODSRESPONSE']._serialized_start=452
  _globals['_LISTVODSRESPONSE']._serialized_end=497
  _globals['_VODSERVICE']._serialized_start=500
  _globals['_VODSERVICE']._serialized_end=687
# @@protoc_insertion_point(module_scope)
