# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts import vod_pb2 as contracts_dot_vod__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in contracts/vod_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VodServiceStub:
    """The VOD service owns playable things. The only field that must exist is the
    playlist URL — an index.m3u8. Title, poster and the rest are metadata the API
    fills in when it has it, and null until then.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateVod = channel.unary_unary(
                '/vod.v1.VodService/CreateVod',
                request_serializer=contracts_dot_vod__pb2.CreateVodRequest.SerializeToString,
                response_deserializer=contracts_dot_vod__pb2.CreateVodResponse.FromString,
                _registered_method=True)
        self.GetVod = channel.unary_unary(
                '/vod.v1.VodService/GetVod',
                request_serializer=contracts_dot_vod__pb2.GetVodRequest.SerializeToString,
                response_deserializer=contracts_dot_vod__pb2.Vod.FromString,
                _registered_method=True)
        self.ListVods = channel.unary_unary(
                '/vod.v1.VodService/ListVods',
                request_serializer=contracts_dot_vod__pb2.ListVodsRequest.SerializeToString,
                response_deserializer=contracts_dot_vod__pb2.ListVodsResponse.FromString,
                _registered_method=True)


class VodServiceServicer:
    """The VOD service owns playable things. The only field that must exist is the
    playlist URL — an index.m3u8. Title, poster and the rest are metadata the API
    fills in when it has it, and null until then.
    """

    def CreateVod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVods(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VodServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateVod': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVod,
                    request_deserializer=contracts_dot_vod__pb2.CreateVodRequest.FromString,
                    response_serializer=contracts_dot_vod__pb2.CreateVodResponse.SerializeToString,
            ),
            'GetVod': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVod,
                    request_deserializer=contracts_dot_vod__pb2.GetVodRequest.FromString,
                    response_serializer=contracts_dot_vod__pb2.Vod.SerializeToString,
            ),
            'ListVods': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVods,
                    request_deserializer=contracts_dot_vod__pb2.ListVodsRequest.FromString,
                    response_serializer=contracts_dot_vod__pb2.ListVodsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vod.v1.VodService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vod.v1.VodService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VodService:
    """The VOD service owns playable things. The only field that must exist is the
    playlist URL — an index.m3u8. Title, poster and the rest are metadata the API
    fills in when it has it, and null until then.
    """

    @staticmethod
    def CreateVod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vod.v1.VodService/CreateVod',
            contracts_dot_vod__pb2.CreateVodRequest.SerializeToString,
            contracts_dot_vod__pb2.CreateVodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vod.v1.VodService/GetVod',
            contracts_dot_vod__pb2.GetVodRequest.SerializeToString,
            contracts_dot_vod__pb2.Vod.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vod.v1.VodService/ListVods',
            contracts_dot_vod__pb2.ListVodsRequest.SerializeToString,
            contracts_dot_vod__pb2.ListVodsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
